route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'singhranand'
  routes:
  - match:
     alertname: target
     receiver: 'null'

receivers:
  - name: 'singhranand'
    email_configs:
    - to: 'anandsing@gmail.com'
      from: 'anandsing@gmail.com'
      auth_username: << add your encrypted username here>>
      auth_password: << add your encrypted password here>>
      require_tls: false
      smarthost: '<< add your smtp host here >>:465'
      send_resolved: true
  - name: 'null'
