# Global Config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.105.2:9093']

rule_files:
   - alert_rules.yml
#to monitor prometheus itself or any other end points
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.105.2:9090']
  - job_name: 'alertmanager'
    static_configs:
        - targets: [ '192.168.105.2:9093' ]
  - job_name: 'nodeExporter'
    static_configs:
        - targets: [ '192.168.105.2:9100' ]
  - job_name: 'cadvidor'
    static_configs:
        - targets: [ '192.168.105.2:8085' ]
  - job_name: 'grafana'
    static_configs:
        - targets: [ '192.168.105.2:3000' ]
#to monitor your VM/server
  - job_name: 'Linux_VM1'
    static_configs:
    - targets: ['192.168.105.2:9100']
